CREDIT_CARDS = [
    {
        "card_name": "SmartSaver Visa Platinum",
        "annual_fee": "$99",
        "interest_rate": "19.99%",
        "rewards": "2% cashback on groceries",
        "requirements": "Minimum income $30,000",
    },
    {
        "card_name": "TravelPlus Mastercard",
        "annual_fee": "$120",
        "interest_rate": "20.99%",
        "rewards": "3x points on flights and hotels",
        "requirements": "Minimum income $50,000",
    },
    {
        "card_name": "StudentEdge Visa",
        "annual_fee": "$0",
        "interest_rate": "21.99%",
        "rewards": "1% cashback on all purchases",
        "requirements": "Student or under 25",
    },
    {
        "card_name": "BusinessMax Visa",
        "annual_fee": "$199",
        "interest_rate": "18.99%",
        "rewards": "3% cashback on office expenses",
        "requirements": "Registered business owner",
    },
    {
        "card_name": "LuxuryElite Mastercard",
        "annual_fee": "$499",
        "interest_rate": "17.99%",
        "rewards": "5x points on travel and dining, airport lounge access",
        "requirements": "Minimum income $120,000",
    },
    {
        "card_name": "EcoRewards Visa",
        "annual_fee": "$79",
        "interest_rate": "20.49%",
        "rewards": "Plant a tree per $100 spent, 1% cashback",
        "requirements": "No specific requirement",
    },
    {
        "card_name": "CashBack Everyday",
        "annual_fee": "$0",
        "interest_rate": "22.99%",
        "rewards": "1.5% cashback on all purchases",
        "requirements": "Minimum income $20,000",
    },
    {
        "card_name": "FuelSaver Mastercard",
        "annual_fee": "$49",
        "interest_rate": "20.99%",
        "rewards": "3% cashback on fuel",
        "requirements": "Minimum income $25,000",
    },
    {
        "card_name": "TechRewards Visa",
        "annual_fee": "$149",
        "interest_rate": "18.99%",
        "rewards": "2x points on electronics and gadgets",
        "requirements": "Minimum income $40,000",
    },
    {
        "card_name": "GlobeTrekker Travel Card",
        "annual_fee": "$129",
        "interest_rate": "20.49%",
        "rewards": "No foreign transaction fees, 2x points on travel",
        "requirements": "Minimum income $60,000",
    },
]
